### ISSUE TITLE
Snippet: Simple demo script

### ISSUE THREAD

**Issue by trasherdk** [trasherdk/Sortable#13]
`html`
```html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>
  
  
<!-- Latest Sortable -->
<script src="https://raw.githack.com/SortableJS/Sortable/master/Sortable.js"></script>
  
  
<!-- Simple List -->
<div class="container">
  <div id="simpleList" class="list-group"></div>
</div>
```
`css`
```css
/* ghostClass */
.ghost {
  opacity: .5;
  color: #C8EBFB !important;
  background: #C8EBFB !important;
}

.drag-preview {
    background: pink;
}

.container {
  /*transform: translateX(0) translateY(0px) rotate(0) skewX(0) skewY(0) scaleX(1) scaleY(1)*/
  transform: rotate(0);
}

body {
  padding: 20px;
}
.list-group-item {
  cursor: move;
}

.list-group {
  height: 400px;
  overflow: auto;
}
```
`javascript`
```js
Sortable.create(simpleList, {ghostClass: 'is-dragged',
        dragClass: 'drag-preview',
        animation: 400,
        scroll: true,
        forceFallback: true,
        scrollSensitivity: 50,
        scrollSpeed: 20, });

// Generate 100 items
simpleList.innerHTML = Array.apply(null,  new Array(100)).map(function (v, i) {
  return '<div class="list-group-item">item ' +
    (i + 1) +
    '</div>';
}).join('');
```
Source 1: https://github.com/SortableJS/Sortable/issues/2101#issuecomment-1128089490
Source 2: https://jsbin.com/jemoqicegu/edit?html,css,js,output
